const songs = {
  "happy": [
    {"title":"Happy","artist":"Pharrell Williams","year":2013,"duration":"3:53"},
    {"title":"Walking on Sunshine","artist":"Katrina & The Waves","year":1985,"duration":"3:59"},
    {"title":"Uptown Funk","artist":"Mark Ronson ft. Bruno Mars","year":2014,"duration":"4:30"},
    {"title":"I Gotta Feeling","artist":"The Black Eyed Peas","year":2009,"duration":"4:49"},
    {"title":"Can't Stop the Feeling!","artist":"Justin Timberlake","year":2016,"duration":"3:56"},
    {"title":"Three Little Birds","artist":"Bob Marley","year":1977,"duration":"3:00"},
    {"title":"Best Day Of My Life","artist":"American Authors","year":2014,"duration":"3:14"},
    {"title":"On Top of the World","artist":"Imagine Dragons","year":2012,"duration":"3:12"},
    {"title":"Shut Up and Dance","artist":"WALK THE MOON","year":2014,"duration":"3:19"},
    {"title":"Ho Gayi Hai Mohabbat","artist":"Arijit Singh","year":2019,"duration":"3:20"},
    {"title":"Ilahi","artist":"Arijit Singh","year":2013,"duration":"3:30"},
    {"title":"Badtameez Dil","artist":"Benny Dayal","year":2013,"duration":"3:08"},
    {"title":"Gallan Goodiyaan","artist":"Yashita Sharma & Ensemble","year":2014,"duration":"5:34"},
    {"title":"Kala Chashma","artist":"Badshah & Neha Kakkar","year":2016,"duration":"3:10"},
    {"title":"London Thumakda","artist":"Sonu Kakkar","year":2013,"duration":"3:35"},
    {"title":"Saturday","artist":"Rebecca Black","year":2011,"duration":"3:05"},
    {"title":"Good as Hell","artist":"Lizzo","year":2016,"duration":"2:39"},
    {"title":"Feel Good Inc.","artist":"Gorillaz","year":2005,"duration":"3:43"},
    {"title":"I'm Yours","artist":"Jason Mraz","year":2008,"duration":"4:02"},
    {"title":"Dog Days Are Over","artist":"Florence + The Machine","year":2008,"duration":"4:12"},
    {"title":"Pompeii","artist":"Bastille","year":2013,"duration":"3:35"},
    {"title":"Viva La Vida","artist":"Coldplay","year":2008,"duration":"4:02"},
    {"title":"Good Time","artist":"Owl City & Carly Rae Jepsen","year":2012,"duration":"3:26"},
    {"title":"Sugar","artist":"Maroon 5","year":2014,"duration":"3:55"},
    {"title":"Cheerleader (Felix Jaehn Remix)","artist":"OMI","year":2015,"duration":"3:00"},
    {"title":"Sunday Morning","artist":"Maroon 5","year":2004,"duration":"4:03"},
    {"title":"Best Song Ever","artist":"One Direction","year":2013,"duration":"3:21"},
    {"title":"Pocketful of Sunshine","artist":"Natasha Bedingfield","year":2008,"duration":"3:27"},
    {"title":"Tamma Tamma Again","artist":"Badshah & Bappi Lahiri","year":2017,"duration":"3:28"},
    {"title":"Galliyaan","artist":"Ankit Tiwari","year":2014,"duration":"4:24"},
    {"title":"London Bridge","artist":"Fergie","year":2006,"duration":"3:26"},
    {"title":"Dance Monkey","artist":"Tones And I","year":2019,"duration":"3:29"},
    {"title":"Cheap Thrills","artist":"Sia","year":2016,"duration":"3:44"},
    {"title":"Abhi Toh Party Shuru Hui Hai","artist":"Badshah","year":2013,"duration":"3:26"},
    {"title":"Saudagar Sauda Karaoke","artist":"Kishore Kumar","year":1973,"duration":"3:10"},
    {"title":"Ainvayi Ainvayi","artist":"Salim-Sulaiman","year":2009,"duration":"4:20"},
    {"title":"Jai Ho!","artist":"A.R. Rahman & The Pussycat Dolls","year":2009,"duration":"3:37"},
    {"title":"Runaway Baby","artist":"Bruno Mars","year":2010,"duration":"2:21"},
    {"title":"Good Life","artist":"OneRepublic","year":2009,"duration":"4:13"},
    {"title":"Put It All On Me","artist":"Ed Sheeran","year":2019,"duration":"3:17"},
    {"title":"Wake Me Up","artist":"Avicii","year":2013,"duration":"4:09"},
    {"title":"Counting Stars","artist":"OneRepublic","year":2013,"duration":"4:17"},
    {"title":"Moves Like Jagger","artist":"Maroon 5 ft. Christina Aguilera","year":2011,"duration":"3:21"},
    {"title":"Hey Ya!","artist":"OutKast","year":2003,"duration":"3:55"},
    {"title":"Mr. Blue Sky","artist":"Electric Light Orchestra","year":1977,"duration":"5:03"},
    {"title":"24K Magic","artist":"Bruno Mars","year":2016,"duration":"3:46"},
    {"title":"Rather Be","artist":"Clean Bandit ft. Jess Glynne","year":2014,"duration":"3:47"},
    {"title":"What Makes You Beautiful","artist":"One Direction","year":2011,"duration":"3:19"},
    {"title":"Firework","artist":"Katy Perry","year":2010,"duration":"3:48"},
    {"title":"Party Rock Anthem","artist":"LMFAO","year":2011,"duration":"4:23"},
    {"title":"Treasure","artist":"Bruno Mars","year":2012,"duration":"2:58"},
    {"title":"Get Lucky","artist":"Daft Punk ft. Pharrell Williams","year":2013,"duration":"6:09"},
    {"title":"Don't Stop Believin'","artist":"Journey","year":1981,"duration":"4:11"},
    {"title":"September","artist":"Earth, Wind & Fire","year":1978,"duration":"3:35"},
    {"title":"Brown Eyed Girl","artist":"Van Morrison","year":1967,"duration":"3:05"},
    {"title":"Here Comes the Sun","artist":"The Beatles","year":1969,"duration":"3:05"},
    {"title":"Lovely Day","artist":"Bill Withers","year":1977,"duration":"4:15"},
    {"title":"Come On Eileen","artist":"Dexys Midnight Runners","year":1982,"duration":"4:12"},
    {"title":"Marry You","artist":"Bruno Mars","year":2010,"duration":"3:50"},
    {"title":"Home","artist":"Phillip Phillips","year":2012,"duration":"3:27"},
    {"title":"Riptide","artist":"Vance Joy","year":2013,"duration":"3:24"},
    {"title":"Good Vibrations","artist":"The Beach Boys","year":1966,"duration":"3:36"},
    {"title":"Build Me Up Buttercup","artist":"The Foundations","year":1968,"duration":"2:59"},
    {"title":"Living on a Prayer","artist":"Bon Jovi","year":1986,"duration":"4:09"},
    {"title":"Dancing Queen","artist":"ABBA","year":1976,"duration":"3:51"},
    {"title":"Isn't She Lovely","artist":"Stevie Wonder","year":1976,"duration":"6:34"},
    {"title":"Valerie","artist":"Amy Winehouse","year":2007,"duration":"3:53"},
    {"title":"Twist and Shout","artist":"The Beatles","year":1963,"duration":"2:33"},
    {"title":"Dynamite","artist":"BTS","year":2020,"duration":"3:19"},
    {"title":"Blinding Lights","artist":"The Weeknd","year":2019,"duration":"3:20"},
    {"title":"Levitating","artist":"Dua Lipa","year":2020,"duration":"3:23"},
    {"title":"Good 4 U","artist":"Olivia Rodrigo","year":2021,"duration":"2:58"},
    {"title":"Shake It Off","artist":"Taylor Swift","year":2014,"duration":"3:39"},
    {"title":"Havana","artist":"Camila Cabello","year":2017,"duration":"3:37"},
    {"title":"Senorita","artist":"Shawn Mendes & Camila Cabello","year":2019,"duration":"3:11"},
    {"title":"Love On Top","artist":"Beyoncé","year":2011,"duration":"4:26"},
    {"title":"Best Friend","artist":"Saweetie ft. Doja Cat","year":2021,"duration":"2:43"},
    {"title":"Roar","artist":"Katy Perry","year":2013,"duration":"3:43"},
    {"title":"Price Tag","artist":"Jessie J","year":2011,"duration":"3:43"},
    {"title":"Call Me Maybe","artist":"Carly Rae Jepsen","year":2011,"duration":"3:13"},
    {"title":"We Are Young","artist":"fun. ft. Janelle Monáe","year":2011,"duration":"4:10"},
    {"title":"Safe and Sound","artist":"Capital Cities","year":2011,"duration":"3:13"},
    {"title":"Ho Hey","artist":"The Lumineers","year":2012,"duration":"2:43"},
    {"title":"Some Nights","artist":"fun.","year":2012,"duration":"4:36"},
    {"title":"Happy Together","artist":"The Turtles","year":1967,"duration":"2:55"},
    {"title":"Can't Stop the Feeling (Remix)","artist":"Justin Timberlake","year":2016,"duration":"3:56"},
    {"title":"Jalebi Baby","artist":"Tesher & Jason Derulo","year":2021,"duration":"2:51"},
    {"title":"Nadiyon Paar","artist":"Sachin-Jigar","year":2020,"duration":"3:31"},
    {"title":"Chandigarh Mein","artist":"Guru Randhawa","year":2020,"duration":"3:03"},
    {"title":"Bachpan Ka Pyaar","artist":"Sahdev Dirdo","year":2021,"duration":"2:48"},
    {"title":"Bijlee Bijlee","artist":"Harrdy Sandhu","year":2021,"duration":"2:54"},
    {"title":"Excuses","artist":"AP Dhillon","year":2020,"duration":"2:58"},
    {"title":"Brown Munde","artist":"AP Dhillon","year":2020,"duration":"3:08"},
    {"title":"Jugnu","artist":"Badshah","year":2020,"duration":"2:44"},
    {"title":"Paagal","artist":"Badshah","year":2019,"duration":"3:04"},
    {"title":"Genda Phool","artist":"Badshah","year":2020,"duration":"2:32"},
    {"title":"Garmi","artist":"Neha Kakkar & Badshah","year":2019,"duration":"4:00"},
    {"title":"Morni Banke","artist":"Guru Randhawa & Neha Kakkar","year":2018,"duration":"3:38"}
  ],
  "sad": [
    {"title":"Someone Like You","artist":"Adele","year":2011,"duration":"4:45"},
    {"title":"Fix You","artist":"Coldplay","year":2005,"duration":"4:55"},
    {"title":"The Scientist","artist":"Coldplay","year":2002,"duration":"5:09"},
    {"title":"When I Was Your Man","artist":"Bruno Mars","year":2012,"duration":"3:34"},
    {"title":"Tere Bina","artist":"A.R. Rahman","year":2006,"duration":"5:02"},
    {"title":"Channa Mereya","artist":"Arijit Singh","year":2016,"duration":"4:56"},
    {"title":"Someone You Loved","artist":"Lewis Capaldi","year":2018,"duration":"3:02"},
    {"title":"Skinny Love","artist":"Bon Iver","year":2007,"duration":"3:58"},
    {"title":"Let Her Go","artist":"Passenger","year":2012,"duration":"4:12"},
    {"title":"Kabira (Encore)","artist":"Arijit Singh","year":2013,"duration":"4:08"},
    {"title":"Bhula Dena","artist":"Mustafa Zahid","year":2008,"duration":"3:58"},
    {"title":"Dil Ibaadat","artist":"Atif Aslam","year":2006,"duration":"4:25"},
    {"title":"Hurt","artist":"Johnny Cash","year":2002,"duration":"3:38"},
    {"title":"Back to December","artist":"Taylor Swift","year":2010,"duration":"4:54"},
    {"title":"All I Want","artist":"Kodaline","year":2013,"duration":"5:07"},
    {"title":"Mann Bharrya","artist":"B Praak","year":2017,"duration":"3:50"},
    {"title":"Agar Tum Saath Ho","artist":"Alka Yagnik & Arijit Singh","year":2015,"duration":"4:26"},
    {"title":"Photograph","artist":"Ed Sheeran","year":2014,"duration":"4:19"},
    {"title":"Say You Love Me","artist":"Jessie Ware","year":2014,"duration":"4:17"},
    {"title":"Tears Dry On Their Own","artist":"Amy Winehouse","year":2006,"duration":"3:06"},
    {"title":"When We Were Young","artist":"Adele","year":2015,"duration":"4:50"},
    {"title":"Judaai","artist":"Arijit Singh","year":2011,"duration":"4:05"},
    {"title":"Kalank Title Track","artist":"Arijit Singh","year":2019,"duration":"5:30"},
    {"title":"The A Team","artist":"Ed Sheeran","year":2011,"duration":"4:18"},
    {"title":"Wake Me Up When September Ends","artist":"Green Day","year":2004,"duration":"4:45"},
    {"title":"Samjhawan","artist":"Arijit Singh","year":2014,"duration":"4:48"},
    {"title":"Dil Ke Armaan","artist":"Kishore Kumar","year":1980,"duration":"3:45"},
    {"title":"Skin","artist":"Raghu Dixit","year":2010,"duration":"4:02"},
    {"title":"Nothing Compares 2 U","artist":"Sinead O'Connor","year":1990,"duration":"5:10"},
    {"title":"I Will Always Love You","artist":"Whitney Houston","year":1992,"duration":"4:31"},
    {"title":"Tum Hi Ho","artist":"Arijit Singh","year":2013,"duration":"4:22"},
    {"title":"Hey There Delilah","artist":"Plain White T's","year":2006,"duration":"3:52"},
    {"title":"Hallelujah","artist":"Jeff Buckley","year":1994,"duration":"6:53"},
    {"title":"Somebody That I Used To Know","artist":"Gotye ft. Kimbra","year":2011,"duration":"4:04"},
    {"title":"Yun Hi Chala Chal","artist":"Sukhwinder Singh","year":2004,"duration":"4:27"},
    {"title":"Jeene Bhi De","artist":"Arijit Singh","year":2019,"duration":"3:34"},
    {"title":"Everybody Hurts","artist":"R.E.M.","year":1992,"duration":"4:56"},
    {"title":"Nahin Saamne","artist":"Anu Malik (sung)","year":1996,"duration":"4:05"},
    {"title":"Unwell","artist":"Matchbox Twenty","year":2003,"duration":"3:50"},
    {"title":"Kabhi Jo Baadal Barse","artist":"Arijit Singh","year":2013,"duration":"5:17"},
    {"title":"The Night We Met","artist":"Lord Huron","year":2015,"duration":"3:28"},
    {"title":"Say Something","artist":"A Great Big World & Christina Aguilera","year":2013,"duration":"3:50"},
    {"title":"Mad World","artist":"Gary Jules","year":2001,"duration":"3:08"},
    {"title":"Creep","artist":"Radiohead","year":1992,"duration":"3:58"},
    {"title":"Fade to Black","artist":"Metallica","year":1984,"duration":"6:57"},
    {"title":"Tears in Heaven","artist":"Eric Clapton","year":1992,"duration":"4:33"},
    {"title":"Yesterday","artist":"The Beatles","year":1965,"duration":"2:05"},
    {"title":"Black","artist":"Pearl Jam","year":1991,"duration":"5:43"},
    {"title":"Nutshell","artist":"Alice in Chains","year":1994,"duration":"4:19"},
    {"title":"How to Save a Life","artist":"The Fray","year":2005,"duration":"4:23"},
    {"title":"Gravity","artist":"John Mayer","year":2006,"duration":"4:03"},
    {"title":"The Sound of Silence","artist":"Simon & Garfunkel","year":1964,"duration":"3:05"},
    {"title":"Cats in the Cradle","artist":"Harry Chapin","year":1974,"duration":"3:45"},
    {"title":"One","artist":"U2","year":1991,"duration":"4:36"},
    {"title":"Iris (Sad Version)","artist":"Goo Goo Dolls","year":1998,"duration":"4:49"},
    {"title":"Breathe Me","artist":"Sia","year":2004,"duration":"4:34"},
    {"title":"Skinny Love (Acoustic)","artist":"Bon Iver","year":2007,"duration":"3:58"},
    {"title":"Falling","artist":"Harry Styles","year":2019,"duration":"4:00"},
    {"title":"drivers license","artist":"Olivia Rodrigo","year":2021,"duration":"4:02"},
    {"title":"When the Party's Over","artist":"Billie Eilish","year":2018,"duration":"3:16"},
    {"title":"lovely","artist":"Billie Eilish & Khalid","year":2018,"duration":"3:20"},
    {"title":"idontwannabeyouanymore","artist":"Billie Eilish","year":2017,"duration":"3:23"},
    {"title":"All Too Well","artist":"Taylor Swift","year":2012,"duration":"5:29"},
    {"title":"Last Kiss","artist":"Taylor Swift","year":2010,"duration":"6:07"},
    {"title":"Soon You'll Get Better","artist":"Taylor Swift","year":2019,"duration":"3:22"},
    {"title":"Jar of Hearts","artist":"Christina Perri","year":2010,"duration":"3:33"},
    {"title":"A Thousand Years","artist":"Christina Perri","year":2011,"duration":"4:45"},
    {"title":"Stay","artist":"Rihanna ft. Mikky Ekko","year":2012,"duration":"4:00"},
    {"title":"We Are Never Getting Back Together","artist":"Taylor Swift","year":2012,"duration":"3:13"},
    {"title":"Apologize","artist":"OneRepublic","year":2007,"duration":"3:26"},
    {"title":"Secrets","artist":"OneRepublic","year":2009,"duration":"3:45"},
    {"title":"Tum Se","artist":"Rahat Fateh Ali Khan","year":2007,"duration":"4:50"},
    {"title":"Aaj Bhi","artist":"Vishal Mishra","year":2018,"duration":"4:30"},
    {"title":"Pachtaoge","artist":"Arijit Singh","year":2019,"duration":"3:38"},
    {"title":"Kaise Hua","artist":"Vishal Mishra","year":2019,"duration":"3:56"},
    {"title":"Bekhayali","artist":"Sachet Tandon","year":2019,"duration":"6:12"},
    {"title":"Pal","artist":"Arijit Singh","year":2018,"duration":"4:24"},
    {"title":"Phir Bhi Tumko Chaahunga","artist":"Arijit Singh","year":2017,"duration":"4:42"},
    {"title":"Hawayein","artist":"Arijit Singh","year":2017,"duration":"5:37"},
    {"title":"Ae Dil Hai Mushkil","artist":"Arijit Singh","year":2016,"duration":"4:29"},
    {"title":"Shayad","artist":"Arijit Singh","year":2020,"duration":"3:46"},
    {"title":"Pehli Dafa","artist":"Atif Aslam","year":2017,"duration":"3:47"},
    {"title":"Dil Diyan Gallan","artist":"Atif Aslam","year":2017,"duration":"3:56"},
    {"title":"Main Rang Sharbaton Ka","artist":"Atif Aslam","year":2013,"duration":"4:44"},
    {"title":"Hasi Ban Gaye","artist":"Ami Mishra","year":2014,"duration":"4:40"},
    {"title":"Muskurane","artist":"Arijit Singh","year":2013,"duration":"4:27"},
    {"title":"Soch Na Sake","artist":"Arijit Singh & Tulsi Kumar","year":2015,"duration":"3:44"},
    {"title":"Yeh Dooriyan","artist":"Mohit Chauhan","year":2011,"duration":"4:41"},
    {"title":"Kahin Door Jab","artist":"Vishal Dadlani","year":2010,"duration":"3:48"},
    {"title":"Tu Jo Mila","artist":"K.K.","year":2015,"duration":"4:37"},
    {"title":"Sanam Re","artist":"Arijit Singh","year":2016,"duration":"4:27"},
    {"title":"Enna Sona","artist":"Arijit Singh","year":2016,"duration":"3:17"},
    {"title":"Zaalima","artist":"Arijit Singh & Harshdeep Kaur","year":2017,"duration":"3:59"},
    {"title":"Humdard","artist":"Arijit Singh","year":2014,"duration":"4:20"},
    {"title":"Saware","artist":"Arijit Singh","year":2014,"duration":"5:11"},
    {"title":"Hamari Adhuri Kahani","artist":"Arijit Singh","year":2015,"duration":"4:47"},
    {"title":"Mein Tenu Samjhawan Ki","artist":"Rahat Fateh Ali Khan","year":2014,"duration":"5:10"}
  ],
  "energetic": [
    {"title":"Lose Yourself","artist":"Eminem","year":2002,"duration":"5:20"},
    {"title":"Enter Sandman","artist":"Metallica","year":1991,"duration":"5:32"},
    {"title":"Smells Like Teen Spirit","artist":"Nirvana","year":1991,"duration":"5:01"},
    {"title":"Bang Bang","artist":"Jessie J, Ariana Grande, Nicki Minaj","year":2014,"duration":"3:19"},
    {"title":"Jai Ho","artist":"A.R. Rahman","year":2008,"duration":"4:16"},
    {"title":"Malhari","artist":"Vishal Dadlani","year":2015,"duration":"3:25"},
    {"title":"Tu Meri Hero","artist":"K.K.","year":2009,"duration":"3:50"},
    {"title":"Stronger","artist":"Kanye West","year":2007,"duration":"5:11"},
    {"title":"Believer","artist":"Imagine Dragons","year":2017,"duration":"3:24"},
    {"title":"Uprising","artist":"Muse","year":2009,"duration":"5:04"},
    {"title":"Aala Re Aala","artist":"Sukhwinder Singh","year":2010,"duration":"3:15"},
    {"title":"Blade Runner","artist":"Vangelis","year":1982,"duration":"5:20"},
    {"title":"Can't Hold Us","artist":"Macklemore & Ryan Lewis","year":2011,"duration":"4:18"},
    {"title":"Jumma Chumma","artist":"Anu Malik (sung)","year":1991,"duration":"5:30"},
    {"title":"Toxic","artist":"Britney Spears","year":2003,"duration":"3:20"},
    {"title":"Bad Guy","artist":"Billie Eilish","year":2019,"duration":"3:14"},
    {"title":"Remember the Name","artist":"Fort Minor","year":2005,"duration":"3:50"},
    {"title":"Nashe Si Chadh Gayi","artist":"Arijit Singh","year":2016,"duration":"3:16"},
    {"title":"Don't Stop Me Now","artist":"Queen","year":1978,"duration":"3:29"},
    {"title":"Boom Clap","artist":"Charli XCX","year":2014,"duration":"3:29"},
    {"title":"High Hopes","artist":"Panic! At The Disco","year":2018,"duration":"3:10"},
    {"title":"Mundian To Bach Ke","artist":"Panjabi MC","year":1998,"duration":"4:42"},
    {"title":"Badtameez Dil (Remix)","artist":"Remix","year":2013,"duration":"3:05"},
    {"title":"Radioactive","artist":"Imagine Dragons","year":2012,"duration":"3:06"},
    {"title":"Pump It","artist":"The Black Eyed Peas","year":2005,"duration":"3:33"},
    {"title":"Let's Get It Started","artist":"The Black Eyed Peas","year":2003,"duration":"3:36"},
    {"title":"Jhoome Jo Pathaan","artist":"Arijit Singh","year":2023,"duration":"3:02"},
    {"title":"Kala Doriya","artist":"Traditional (modern remixes)","year":2018,"duration":"3:45"},
    {"title":"Power","artist":"Kanye West","year":2010,"duration":"4:52"},
    {"title":"The Nights","artist":"Avicii","year":2014,"duration":"2:56"},
    {"title":"Tunak Tunak Tun","artist":"Daler Mehndi","year":1998,"duration":"4:40"},
    {"title":"Eye of the Tiger","artist":"Survivor","year":1982,"duration":"4:05"},
    {"title":"Pump Up The Jam","artist":"Technotronic","year":1989,"duration":"5:14"},
    {"title":"Buniyaad","artist":"Vishal & Shekhar","year":2011,"duration":"3:45"},
    {"title":"Break Free","artist":"Ariana Grande ft. Zedd","year":2014,"duration":"3:34"},
    {"title":"Harder Better Faster Stronger","artist":"Daft Punk","year":2001,"duration":"3:44"},
    {"title":"Bad Reputation","artist":"Joan Jett","year":1980,"duration":"2:48"},
    {"title":"Jhandu Billi","artist":"Remix/Indie","year":2017,"duration":"3:20"},
    {"title":"Funky Town","artist":"Lipps Inc.","year":1980,"duration":"3:58"},
    {"title":"Thunder","artist":"Imagine Dragons","year":2017,"duration":"3:07"},
    {"title":"Whatever It Takes","artist":"Imagine Dragons","year":2017,"duration":"3:21"},
    {"title":"Natural","artist":"Imagine Dragons","year":2018,"duration":"3:09"},
    {"title":"Warriors","artist":"Imagine Dragons","year":2014,"duration":"2:50"},
    {"title":"It's My Life","artist":"Bon Jovi","year":2000,"duration":"3:44"},
    {"title":"You Give Love a Bad Name","artist":"Bon Jovi","year":1986,"duration":"3:42"},
    {"title":"We Will Rock You","artist":"Queen","year":1977,"duration":"2:02"},
    {"title":"We Are the Champions","artist":"Queen","year":1977,"duration":"2:59"},
    {"title":"Another One Bites the Dust","artist":"Queen","year":1980,"duration":"3:35"},
    {"title":"Immigrant Song","artist":"Led Zeppelin","year":1970,"duration":"2:26"},
    {"title":"Kashmir","artist":"Led Zeppelin","year":1975,"duration":"8:37"},
    {"title":"Back in Black","artist":"AC/DC","year":1980,"duration":"4:15"},
    {"title":"Highway to Hell","artist":"AC/DC","year":1979,"duration":"3:28"},
    {"title":"Thunderstruck","artist":"AC/DC","year":1990,"duration":"4:52"},
    {"title":"Crazy Train","artist":"Ozzy Osbourne","year":1980,"duration":"4:50"},
    {"title":"Master of Puppets","artist":"Metallica","year":1986,"duration":"8:35"},
    {"title":"One","artist":"Metallica","year":1988,"duration":"7:27"},
    {"title":"Welcome to the Jungle","artist":"Guns N' Roses","year":1987,"duration":"4:31"},
    {"title":"Sweet Child O' Mine","artist":"Guns N' Roses","year":1987,"duration":"5:56"},
    {"title":"Paradise City","artist":"Guns N' Roses","year":1988,"duration":"6:46"},
    {"title":"Born to Run","artist":"Bruce Springsteen","year":1975,"duration":"4:30"},
    {"title":"Blitzkrieg Bop","artist":"Ramones","year":1976,"duration":"2:12"},
    {"title":"Should I Stay or Should I Go","artist":"The Clash","year":1982,"duration":"3:07"},
    {"title":"London Calling","artist":"The Clash","year":1979,"duration":"3:19"},
    {"title":"Paranoid","artist":"Black Sabbath","year":1970,"duration":"2:48"},
    {"title":"Seven Nation Army","artist":"The White Stripes","year":2003,"duration":"3:52"},
    {"title":"Killing in the Name","artist":"Rage Against the Machine","year":1992,"duration":"5:14"},
    {"title":"Bulls on Parade","artist":"Rage Against the Machine","year":1996,"duration":"3:51"},
    {"title":"Sabotage","artist":"Beastie Boys","year":1994,"duration":"2:58"},
    {"title":"(You Gotta) Fight for Your Right (To Party!)","artist":"Beastie Boys","year":1986,"duration":"3:29"},
    {"title":"Till I Collapse","artist":"Eminem","year":2002,"duration":"4:57"},
    {"title":"Without Me","artist":"Eminem","year":2002,"duration":"4:50"},
    {"title":"The Real Slim Shady","artist":"Eminem","year":2000,"duration":"4:44"},
    {"title":"Run This Town","artist":"Jay-Z ft. Rihanna & Kanye West","year":2009,"duration":"4:27"},
    {"title":"N.I.B.","artist":"Black Sabbath","year":1970,"duration":"6:08"},
    {"title":"War Pigs","artist":"Black Sabbath","year":1970,"duration":"7:57"},
    {"title":"Iron Man","artist":"Black Sabbath","year":1970,"duration":"5:56"},
    {"title":"Ace of Spades","artist":"Motörhead","year":1980,"duration":"2:49"},
    {"title":"Run to the Hills","artist":"Iron Maiden","year":1982,"duration":"3:54"},
    {"title":"The Trooper","artist":"Iron Maiden","year":1983,"duration":"4:11"},
    {"title":"Painkiller","artist":"Judas Priest","year":1990,"duration":"6:06"},
    {"title":"Breaking the Law","artist":"Judas Priest","year":1980,"duration":"2:35"},
    {"title":"Du Hast","artist":"Rammstein","year":1997,"duration":"3:54"},
    {"title":"Chop Suey!","artist":"System of a Down","year":2001,"duration":"3:30"},
    {"title":"Toxicity","artist":"System of a Down","year":2001,"duration":"3:39"},
    {"title":"Freak on a Leash","artist":"Korn","year":1998,"duration":"4:15"},
    {"title":"In the End","artist":"Linkin Park","year":2000,"duration":"3:36"},
    {"title":"Numb","artist":"Linkin Park","year":2003,"duration":"3:07"},
    {"title":"What I've Done","artist":"Linkin Park","year":2007,"duration":"3:25"},
    {"title":"Faint","artist":"Linkin Park","year":2003,"duration":"2:42"},
    {"title":"Papercut","artist":"Linkin Park","year":2000,"duration":"3:04"},
    {"title":"Given Up","artist":"Linkin Park","year":2007,"duration":"3:09"},
    {"title":"Bleed It Out","artist":"Linkin Park","year":2007,"duration":"2:44"},
    {"title":"One Step Closer","artist":"Linkin Park","year":2000,"duration":"2:36"},
    {"title":"Animal I Have Become","artist":"Three Days Grace","year":2006,"duration":"3:51"},
    {"title":"Riot","artist":"Three Days Grace","year":2006,"duration":"3:27"},
    {"title":"I Hate Everything About You","artist":"Three Days Grace","year":2003,"duration":"3:50"},
    {"title":"Pain","artist":"Three Days Grace","year":2006,"duration":"3:23"},
    {"title":"Click Click Boom","artist":"Saliva","year":2001,"duration":"4:15"}
  ],
  "romantic": [
    {"title":"Perfect","artist":"Ed Sheeran","year":2017,"duration":"4:23"},
    {"title":"Tum Hi Ho","artist":"Arijit Singh","year":2013,"duration":"4:22"},
    {"title":"All of Me","artist":"John Legend","year":2013,"duration":"4:30"},
    {"title":"Pee Loon","artist":"Mohit Chauhan","year":2008,"duration":"4:24"},
    {"title":"Make You Feel My Love","artist":"Adele","year":2008,"duration":"3:32"},
    {"title":"Tera Ban Jaunga","artist":"Akhil Sachdeva","year":2019,"duration":"3:50"},
    {"title":"Die A Happy Man","artist":"Thomas Rhett","year":2015,"duration":"3:36"},
    {"title":"Tum Se Hi","artist":"Mohit Chauhan","year":2006,"duration":"5:30"},
    {"title":"I Don't Want to Miss a Thing","artist":"Aerosmith","year":1998,"duration":"4:59"},
    {"title":"Janam Janam","artist":"Arijit Singh","year":2015,"duration":"6:24"},
    {"title":"Kuch Kuch Hota Hai Title","artist":"Kumar Sanu & Alka Yagnik","year":1998,"duration":"4:30"},
    {"title":"My Heart Will Go On","artist":"Celine Dion","year":1997,"duration":"4:40"},
    {"title":"Tum Mile","artist":"Neeraj Shridhar","year":2009,"duration":"4:02"},
    {"title":"Thinking Out Loud","artist":"Ed Sheeran","year":2014,"duration":"4:41"},
    {"title":"Raabta","artist":"Arijit Singh","year":2012,"duration":"4:33"},
    {"title":"Your Song","artist":"Elton John","year":1970,"duration":"4:02"},
    {"title":"Raazi Title Track","artist":"Shankar Ehsaan Loy","year":2018,"duration":"3:50"},
    {"title":"Atif Aslam - Tere Sang Yaara","artist":"Atif Aslam","year":2016,"duration":"4:26"},
    {"title":"Kiss Me","artist":"Sixpence None the Richer","year":1997,"duration":"3:28"},
    {"title":"Pehla Nasha","artist":"Udit Narayan","year":1992,"duration":"5:25"},
    {"title":"Say You Won't Let Go","artist":"James Arthur","year":2016,"duration":"3:31"},
    {"title":"Tera Hone Laga Hoon","artist":"Atif Aslam & Alisha Chinai","year":2006,"duration":"3:37"},
    {"title":"Iris","artist":"Goo Goo Dolls","year":1998,"duration":"4:49"},
    {"title":"Tum Jo Aaye","artist":"Rahul Pandit","year":2007,"duration":"5:22"},
    {"title":"Come Away With Me","artist":"Norah Jones","year":2002,"duration":"3:18"},
    {"title":"Gerua","artist":"Arijit Singh","year":2015,"duration":"4:50"},
    {"title":"Just The Way You Are","artist":"Bruno Mars","year":2010,"duration":"3:40"},
    {"title":"Tujh Mein Rab Dikhta Hai","artist":"Roop Kumar Rathod","year":2008,"duration":"4:44"},
    {"title":"Have I Told You Lately","artist":"Van Morrison","year":1989,"duration":"4:18"},
    {"title":"Ik Vaari Aa","artist":"Arijit Singh","year":2018,"duration":"4:50"},
    {"title":"We Found Love","artist":"Rihanna ft. Calvin Harris","year":2011,"duration":"3:35"},
    {"title":"Tum Se Hi (Reprise)","artist":"A.R. Rahman","year":2006,"duration":"4:10"},
    {"title":"Kya Mujhe Pyar Hai","artist":"K.K.","year":2006,"duration":"3:57"},
    {"title":"Unchained Melody","artist":"The Righteous Brothers","year":1965,"duration":"3:38"},
    {"title":"Tera Ban Jaunga (Acoustic)","artist":"Akhil Sachdeva","year":2019,"duration":"3:40"},
    {"title":"I Choose You","artist":"Sara Bareilles","year":2013,"duration":"3:40"},
    {"title":"Tera Mera Pyar","artist":"Classic Bollywood","year":1976,"duration":"4:02"},
    {"title":"All My Life","artist":"K-Ci & JoJo","year":1997,"duration":"5:31"},
    {"title":"Kinna Sona","artist":"Sunil Kamath","year":2015,"duration":"4:09"},
    {"title":"At Last","artist":"Etta James","year":1960,"duration":"3:00"},
    {"title":"Wonderful Tonight","artist":"Eric Clapton","year":1977,"duration":"3:43"},
    {"title":"Endless Love","artist":"Diana Ross & Lionel Richie","year":1981,"duration":"4:27"},
    {"title":"Can't Help Falling in Love","artist":"Elvis Presley","year":1961,"duration":"3:00"},
    {"title":"Stand By Me","artist":"Ben E. King","year":1961,"duration":"2:57"},
    {"title":"What a Wonderful World","artist":"Louis Armstrong","year":1967,"duration":"2:21"},
    {"title":"The Way You Look Tonight","artist":"Frank Sinatra","year":1964,"duration":"3:22"},
    {"title":"Moon River","artist":"Audrey Hepburn","year":1961,"duration":"2:41"},
    {"title":"La Vie En Rose","artist":"Édith Piaf","year":1947,"duration":"3:06"},
    {"title":"A Thousand Years","artist":"Christina Perri","year":2011,"duration":"4:45"},
    {"title":"Marry Me","artist":"Train","year":2010,"duration":"3:54"},
    {"title":"Everything","artist":"Michael Bublé","year":2007,"duration":"3:55"},
    {"title":"Home","artist":"Michael Bublé","year":2005,"duration":"3:52"},
    {"title":"Haven't Met You Yet","artist":"Michael Bublé","year":2009,"duration":"4:06"},
    {"title":"L-O-V-E","artist":"Nat King Cole","year":1965,"duration":"2:23"},
    {"title":"Unforgettable","artist":"Nat King Cole","year":1951,"duration":"3:28"},
    {"title":"The Power of Love","artist":"Celine Dion","year":1993,"duration":"5:39"},
    {"title":"Because You Loved Me","artist":"Celine Dion","year":1996,"duration":"4:34"},
    {"title":"I Will Always Love You (Ballad)","artist":"Whitney Houston","year":1992,"duration":"4:31"},
    {"title":"Greatest Love of All","artist":"Whitney Houston","year":1985,"duration":"4:52"},
    {"title":"How Deep Is Your Love","artist":"Bee Gees","year":1977,"duration":"4:05"},
    {"title":"More Than Words","artist":"Extreme","year":1990,"duration":"5:34"},
    {"title":"I'll Be There","artist":"The Jackson 5","year":1970,"duration":"3:57"},
    {"title":"Lady in Red","artist":"Chris de Burgh","year":1986,"duration":"4:17"},
    {"title":"Open Arms","artist":"Journey","year":1981,"duration":"3:20"},
    {"title":"Faithfully","artist":"Journey","year":1983,"duration":"4:26"},
    {"title":"Always","artist":"Bon Jovi","year":1994,"duration":"5:52"},
    {"title":"Bed of Roses","artist":"Bon Jovi","year":1992,"duration":"6:33"},
    {"title":"I Don't Wanna Miss a Thing (Acoustic)","artist":"Aerosmith","year":1998,"duration":"4:59"},
    {"title":"The Luckiest","artist":"Ben Folds","year":2001,"duration":"4:27"},
    {"title":"In My Life","artist":"The Beatles","year":1965,"duration":"2:27"},
    {"title":"Something","artist":"The Beatles","year":1969,"duration":"3:03"},
    {"title":"God Only Knows","artist":"The Beach Boys","year":1966,"duration":"2:51"},
    {"title":"Make You Feel My Love (Acoustic)","artist":"Bob Dylan","year":1997,"duration":"3:32"},
    {"title":"Songbird","artist":"Fleetwood Mac","year":1977,"duration":"3:21"},
    {"title":"Landslide","artist":"Fleetwood Mac","year":1975,"duration":"3:19"},
    {"title":"The One","artist":"Kodaline","year":2013,"duration":"4:03"},
    {"title":"Love Someone","artist":"Lukas Graham","year":2018,"duration":"3:36"},
    {"title":"Sucker","artist":"Jonas Brothers","year":2019,"duration":"3:01"},
    {"title":"Sunday Morning (Acoustic)","artist":"Maroon 5","year":2004,"duration":"4:03"},
    {"title":"She Will Be Loved","artist":"Maroon 5","year":2004,"duration":"4:17"},
    {"title":"This Love","artist":"Maroon 5","year":2004,"duration":"3:26"},
    {"title":"Love Story","artist":"Taylor Swift","year":2008,"duration":"3:55"},
    {"title":"Mine","artist":"Taylor Swift","year":2010,"duration":"3:51"},
    {"title":"Begin Again","artist":"Taylor Swift","year":2012,"duration":"3:57"},
    {"title":"Everything Has Changed","artist":"Taylor Swift ft. Ed Sheeran","year":2012,"duration":"4:03"},
    {"title":"Wildest Dreams","artist":"Taylor Swift","year":2014,"duration":"3:40"},
    {"title":"Lover","artist":"Taylor Swift","year":2019,"duration":"3:41"},
    {"title":"Sparks Fly","artist":"Taylor Swift","year":2010,"duration":"4:22"},
    {"title":"Enchanted","artist":"Taylor Swift","year":2010,"duration":"5:52"},
    {"title":"You Belong With Me","artist":"Taylor Swift","year":2008,"duration":"3:51"},
    {"title":"Love Me Like You Do","artist":"Ellie Goulding","year":2015,"duration":"4:10"},
    {"title":"How Long Will I Love You","artist":"Ellie Goulding","year":2013,"duration":"3:27"},
    {"title":"Lights","artist":"Ellie Goulding","year":2010,"duration":"3:30"},
    {"title":"Latch (Acoustic)","artist":"Sam Smith","year":2012,"duration":"4:16"},
    {"title":"Lay Me Down","artist":"Sam Smith","year":2014,"duration":"4:13"},
    {"title":"Not the Only One","artist":"Sam Smith","year":2014,"duration":"3:59"},
    {"title":"Stay With Me","artist":"Sam Smith","year":2014,"duration":"2:52"},
    {"title":"Halo","artist":"Beyoncé","year":2008,"duration":"4:21"}
  ],
  "chill": [
    {"title":"Lo-Fi Chill Beats","artist":"Various Artists","year":2018,"duration":"2:58"},
    {"title":"Sunset Lover","artist":"Petit Biscuit","year":2015,"duration":"3:57"},
    {"title":"Night Owl","artist":"Galimatias","year":2017,"duration":"3:30"},
    {"title":"Cold Little Heart","artist":"Michael Kiwanuka","year":2016,"duration":"10:08"},
    {"title":"Khwaja","artist":"Qawwali (fusion)","year":2010,"duration":"5:12"},
    {"title":"Let Her Go (Acoustic)","artist":"Passenger","year":2012,"duration":"3:15"},
    {"title":"Nadaan Parindey","artist":"Mohit Chauhan","year":2011,"duration":"5:30"},
    {"title":"Lost","artist":"Frank Ocean","year":2012,"duration":"3:54"},
    {"title":"Luka Chuppi (Gentle)","artist":"A.R. Rahman","year":1998,"duration":"4:00"},
    {"title":"Tere Bina (Acoustic)","artist":"A.R. Rahman (stripped)","year":2006,"duration":"4:20"},
    {"title":"Holocene","artist":"Bon Iver","year":2011,"duration":"5:36"},
    {"title":"Teardrop","artist":"Massive Attack","year":1998,"duration":"5:31"},
    {"title":"River Flows In You","artist":"Yiruma","year":2001,"duration":"3:05"},
    {"title":"Patakha Guddi (Female)","artist":"Nooran Sisters","year":2011,"duration":"6:33"},
    {"title":"Breathe Me","artist":"Sia","year":2004,"duration":"4:34"},
    {"title":"Postcards From Far Away","artist":"Coldplay (instrumental vibe)","year":2011,"duration":"3:10"},
    {"title":"Sunscreen","artist":"DJ Chill Mix","year":2016,"duration":"3:50"},
    {"title":"Mora Saiyaan","artist":"Fuzön","year":2003,"duration":"5:00"},
    {"title":"Holocene (Live)","artist":"Bon Iver","year":2012,"duration":"4:20"},
    {"title":"Come Away With Me (Live)","artist":"Norah Jones","year":2002,"duration":"3:40"},
    {"title":"Tere Sang Yaara (Acoustic)","artist":"Atif Aslam","year":2016,"duration":"3:30"},
    {"title":"Lofi Nights","artist":"Various Artists","year":2019,"duration":"2:50"},
    {"title":"Love Like Ghosts (Instrumental)","artist":"Lord Huron","year":2012,"duration":"3:50"},
    {"title":"Tu Hai Ki Nahi (Soft)","artist":"Ankit Tiwari","year":2015,"duration":"4:05"},
    {"title":"Bloom","artist":"The Paper Kites","year":2010,"duration":"3:58"},
    {"title":"Suno Aisha","artist":"Vishal-Shekhar (soft)","year":2010,"duration":"3:50"},
    {"title":"Weightless","artist":"Marconi Union","year":2011,"duration":"8:00"},
    {"title":"Cold Little Heart (Short)","artist":"Michael Kiwanuka","year":2016,"duration":"4:20"},
    {"title":"Raabta (Cafe)","artist":"Indie Remix","year":2017,"duration":"3:40"},
    {"title":"Night Drive","artist":"Chromatics","year":2012,"duration":"4:00"},
    {"title":"Kahin Toh Hogi Woh","artist":"Rahat Fateh Ali Khan","year":2008,"duration":"5:05"},
    {"title":"Slow Dancing in a Burning Room","artist":"John Mayer","year":2006,"duration":"4:02"},
    {"title":"Agar Tum Saath Ho (Soft)","artist":"Alka Yagnik & Arijit Singh","year":2015,"duration":"4:30"},
    {"title":"Afterglow","artist":"Ed Sheeran","year":2020,"duration":"3:06"},
    {"title":"Ocean Eyes","artist":"Billie Eilish","year":2016,"duration":"3:20"},
    {"title":"Naina","artist":"Arijit Singh","year":2016,"duration":"4:20"},
    {"title":"The Story","artist":"Norah Jones","year":2016,"duration":"4:15"},
    {"title":"Kabira (Arijit)","artist":"Arijit Singh (soft)","year":2013,"duration":"4:10"},
    {"title":"Sajde","artist":"K.K.","year":2008,"duration":"5:05"},
    {"title":"Dreams","artist":"Fleetwood Mac","year":1977,"duration":"4:17"},
    {"title":"Kahin To Mile","artist":"Mika Singh (soft)","year":2003,"duration":"4:10"},
    {"title":"Late Night Drives","artist":"Instrumental Mix","year":2019,"duration":"3:35"},
    {"title":"Pink + White","artist":"Frank Ocean","year":2016,"duration":"3:04"},
    {"title":"Self Control","artist":"Frank Ocean","year":2016,"duration":"9:10"},
    {"title":"Ivy","artist":"Frank Ocean","year":2016,"duration":"4:09"},
    {"title":"Nights","artist":"Frank Ocean","year":2016,"duration":"5:07"},
    {"title":"White Ferrari","artist":"Frank Ocean","year":2016,"duration":"4:08"},
    {"title":"Solo","artist":"Frank Ocean","year":2016,"duration":"4:17"},
    {"title":"Nikes","artist":"Frank Ocean","year":2016,"duration":"5:14"},
    {"title":"Pyramids","artist":"Frank Ocean","year":2012,"duration":"9:53"},
    {"title":"Thinkin Bout You","artist":"Frank Ocean","year":2012,"duration":"3:20"},
    {"title":"Novacane","artist":"Frank Ocean","year":2011,"duration":"4:13"},
    {"title":"Swim Good","artist":"Frank Ocean","year":2011,"duration":"4:19"},
    {"title":"Super Rich Kids","artist":"Frank Ocean","year":2012,"duration":"5:04"},
    {"title":"Chanel","artist":"Frank Ocean","year":2017,"duration":"3:30"},
    {"title":"Provider","artist":"Frank Ocean","year":2017,"duration":"4:16"},
    {"title":"Moon River (Acoustic)","artist":"Frank Ocean","year":2018,"duration":"3:31"},
    {"title":"Godspeed","artist":"Frank Ocean","year":2016,"duration":"3:09"},
    {"title":"Siegfried","artist":"Frank Ocean","year":2016,"duration":"5:34"},
    {"title":"Futura Free","artist":"Frank Ocean","year":2016,"duration":"9:25"},
    {"title":"Close to You","artist":"Frank Ocean","year":2013,"duration":"3:01"},
    {"title":"Swim Good (Acoustic)","artist":"Frank Ocean","year":2011,"duration":"4:00"},
    {"title":"Bad Religion","artist":"Frank Ocean","year":2012,"duration":"2:50"},
    {"title":"Forrest Gump","artist":"Frank Ocean","year":2012,"duration":"3:16"},
    {"title":"Crack Rock","artist":"Frank Ocean","year":2012,"duration":"3:43"},
    {"title":"Sweet Life","artist":"Frank Ocean","year":2012,"duration":"4:23"},
    {"title":"Pink Matter","artist":"Frank Ocean ft. André 3000","year":2012,"duration":"4:33"},
    {"title":"Pilot Jones","artist":"Frank Ocean","year":2012,"duration":"3:01"},
    {"title":"Lost (Acoustic)","artist":"Frank Ocean","year":2012,"duration":"3:40"},
    {"title":"Monks","artist":"Frank Ocean","year":2012,"duration":"3:27"},
    {"title":"Voodoo","artist":"Frank Ocean","year":2013,"duration":"3:24"},
    {"title":"Blue Whale","artist":"Frank Ocean","year":2013,"duration":"3:43"},
    {"title":"Wiseman","artist":"Frank Ocean","year":2013,"duration":"3:32"},
    {"title":"Alabama","artist":"John Coltrane","year":1963,"duration":"5:13"},
    {"title":"In a Sentimental Mood","artist":"Duke Ellington & John Coltrane","year":1963,"duration":"4:16"},
    {"title":"Naima","artist":"John Coltrane","year":1959,"duration":"4:24"},
    {"title":"Flamenco Sketches","artist":"Miles Davis","year":1959,"duration":"9:26"},
    {"title":"Blue in Green","artist":"Miles Davis","year":1959,"duration":"5:37"},
    {"title":"So What","artist":"Miles Davis","year":1959,"duration":"9:25"},
    {"title":"All Blues","artist":"Miles Davis","year":1959,"duration":"11:35"},
    {"title":"Freddie Freeloader","artist":"Miles Davis","year":1959,"duration":"9:49"},
    {"title":"Autumn Leaves","artist":"Bill Evans","year":1960,"duration":"5:04"},
    {"title":"Waltz for Debby","artist":"Bill Evans","year":1961,"duration":"6:52"},
    {"title":"My Foolish Heart","artist":"Bill Evans","year":1961,"duration":"4:56"},
    {"title":"Summertime","artist":"Bill Evans","year":1962,"duration":"10:36"},
    {"title":"Peace Piece","artist":"Bill Evans","year":1958,"duration":"6:44"},
    {"title":"Blue Bossa","artist":"Joe Henderson","year":1963,"duration":"8:37"},
    {"title":"Recorda Me","artist":"Joe Henderson","year":1963,"duration":"6:50"},
    {"title":"On Green Dolphin Street","artist":"Bill Evans","year":1959,"duration":"10:04"},
    {"title":"Solar","artist":"Miles Davis","year":1954,"duration":"4:46"},
    {"title":"Stella by Starlight","artist":"Various Jazz Artists","year":1958,"duration":"5:15"},
    {"title":"Take Five","artist":"Dave Brubeck","year":1959,"duration":"5:24"},
    {"title":"Blue Rondo à la Turk","artist":"Dave Brubeck","year":1959,"duration":"6:44"},
    {"title":"My Favorite Things","artist":"John Coltrane","year":1961,"duration":"13:43"},
    {"title":"Round Midnight","artist":"Thelonious Monk","year":1956,"duration":"6:01"},
    {"title":"Moanin'","artist":"Art Blakey","year":1958,"duration":"9:33"}
  ],
  "motivational": [
    {"title":"Eye of the Tiger","artist":"Survivor","year":1982,"duration":"4:05"},
    {"title":"Lose Yourself","artist":"Eminem","year":2002,"duration":"5:20"},
    {"title":"Hall of Fame","artist":"The Script ft. will.i.am","year":2012,"duration":"3:22"},
    {"title":"Roar","artist":"Katy Perry","year":2013,"duration":"3:43"},
    {"title":"Believer","artist":"Imagine Dragons","year":2017,"duration":"3:24"},
    {"title":"Zinda","artist":"Bhaiyyu","year":2009,"duration":"4:01"},
    {"title":"Kuch Khaas","artist":"A.R. Rahman (uplifting)","year":2011,"duration":"3:50"},
    {"title":"Fight Song","artist":"Rachel Platten","year":2015,"duration":"3:24"},
    {"title":"Can't Hold Us","artist":"Macklemore & Ryan Lewis","year":2011,"duration":"4:18"},
    {"title":"Jai Ho (You Are My Destiny)","artist":"A.R. Rahman & The Pussycat Dolls","year":2009,"duration":"3:35"},
    {"title":"Stronger","artist":"Kelly Clarkson","year":2011,"duration":"3:41"},
    {"title":"The Man","artist":"Aloe Blacc","year":2014,"duration":"3:22"},
    {"title":"Kar Har Maidaan Fateh","artist":"Sukhwinder Singh","year":2018,"duration":"4:32"},
    {"title":"Champion","artist":"Kylie Minogue","year":2014,"duration":"3:56"},
    {"title":"Can't Stop","artist":"Red Hot Chili Peppers","year":2002,"duration":"4:29"},
    {"title":"On Top of the World","artist":"Imagine Dragons","year":2012,"duration":"3:12"},
    {"title":"Aashayein","artist":"KK","year":2007,"duration":"4:24"},
    {"title":"Not Afraid","artist":"Eminem","year":2010,"duration":"4:08"},
    {"title":"Remember the Name","artist":"Fort Minor","year":2005,"duration":"3:50"},
    {"title":"Whatever It Takes","artist":"Imagine Dragons","year":2017,"duration":"3:21"},
    {"title":"Hall of Fame (Chorus)","artist":"The Script","year":2012,"duration":"3:20"},
    {"title":"Roobaroo","artist":"A.R. Rahman","year":2004,"duration":"5:03"},
    {"title":"New Day","artist":"50 Cent","year":2014,"duration":"4:10"},
    {"title":"Survivor","artist":"Destiny's Child","year":2001,"duration":"4:14"},
    {"title":"Ziddi Dil","artist":"Swaggers","year":2015,"duration":"3:30"},
    {"title":"Hall of Fame (Remix)","artist":"DJ Motivational Mix","year":2016,"duration":"3:45"},
    {"title":"Rise","artist":"Katy Perry","year":2016,"duration":"3:23"},
    {"title":"Apna Time Aayega (Remix)","artist":"Divine","year":2019,"duration":"3:15"},
    {"title":"Lose Yourself (Short)","artist":"Eminem","year":2002,"duration":"3:30"},
    {"title":"Roar (Instrumental)","artist":"Piano Mix","year":2015,"duration":"3:10"},
    {"title":"Aashayein (Live)","artist":"KK (live)","year":2007,"duration":"4:00"},
    {"title":"Champion (Alternate)","artist":"Various Artists","year":2018,"duration":"3:40"},
    {"title":"We Will Rock You","artist":"Queen","year":1977,"duration":"2:02"},
    {"title":"Hall of Fame (Acoustic)","artist":"The Script","year":2012,"duration":"3:50"},
    {"title":"Zidd","artist":"Rock Anthem","year":2016,"duration":"3:55"},
    {"title":"Jai Ho (Instrumental)","artist":"A.R. Rahman (score)","year":2008,"duration":"3:05"},
    {"title":"Fighter","artist":"Christina Aguilera","year":2002,"duration":"4:06"},
    {"title":"Apna Time Aayega","artist":"Ranveer Singh","year":2019,"duration":"3:45"},
    {"title":"Remember The Name (Short)","artist":"Fort Minor","year":2005,"duration":"2:50"},
    {"title":"Not Afraid (Radio Edit)","artist":"Eminem","year":2010,"duration":"4:00"},
    {"title":"Zinda (Live)","artist":"Bhaiyyu (live)","year":2010,"duration":"4:30"},
    {"title":"Best of You","artist":"Foo Fighters","year":2005,"duration":"4:16"},
    {"title":"Eye of the Tiger (Short)","artist":"Survivor","year":1982,"duration":"2:45"},
    {"title":"Stronger (What Doesn't Kill You)","artist":"Kelly Clarkson","year":2011,"duration":"3:41"},
    {"title":"Titanium","artist":"David Guetta ft. Sia","year":2011,"duration":"4:05"},
    {"title":"The Champion","artist":"Carrie Underwood ft. Ludacris","year":2018,"duration":"3:07"},
    {"title":"Unstoppable","artist":"Sia","year":2016,"duration":"3:37"},
    {"title":"This Is Me","artist":"Keala Settle","year":2017,"duration":"3:54"},
    {"title":"Centuries","artist":"Fall Out Boy","year":2014,"duration":"3:48"},
    {"title":"My Songs Know What You Did in the Dark","artist":"Fall Out Boy","year":2013,"duration":"3:06"},
    {"title":"The Phoenix","artist":"Fall Out Boy","year":2013,"duration":"4:03"},
    {"title":"Counting Stars (Motivational)","artist":"OneRepublic","year":2013,"duration":"4:17"},
    {"title":"Something Just Like This","artist":"The Chainsmokers & Coldplay","year":2017,"duration":"4:07"},
    {"title":"Heroes","artist":"David Bowie","year":1977,"duration":"6:07"},
    {"title":"Don't Stop Believin' (Motivational)","artist":"Journey","year":1981,"duration":"4:11"},
    {"title":"Ain't No Mountain High Enough","artist":"Marvin Gaye & Tammi Terrell","year":1967,"duration":"2:30"},
    {"title":"I'm Still Standing","artist":"Elton John","year":1983,"duration":"3:03"},
    {"title":"Unwritten","artist":"Natasha Bedingfield","year":2004,"duration":"4:18"},
    {"title":"Brave","artist":"Sara Bareilles","year":2013,"duration":"3:40"},
    {"title":"Beautiful","artist":"Christina Aguilera","year":2002,"duration":"3:58"},
    {"title":"Born This Way","artist":"Lady Gaga","year":2011,"duration":"4:20"},
    {"title":"Firework (Motivational)","artist":"Katy Perry","year":2010,"duration":"3:48"},
    {"title":"Try","artist":"P!nk","year":2012,"duration":"4:07"},
    {"title":"Just Like Fire","artist":"P!nk","year":2016,"duration":"3:33"},
    {"title":"What Doesn't Kill You","artist":"Kelly Clarkson","year":2011,"duration":"3:42"},
    {"title":"Skyscraper","artist":"Demi Lovato","year":2011,"duration":"3:57"},
    {"title":"Confident","artist":"Demi Lovato","year":2015,"duration":"3:27"},
    {"title":"Sorry Not Sorry","artist":"Demi Lovato","year":2017,"duration":"3:24"},
    {"title":"This Is How We Do It","artist":"Montell Jordan","year":1995,"duration":"4:03"},
    {"title":"Gonna Fly Now","artist":"Bill Conti","year":1976,"duration":"2:47"},
    {"title":"We Are the Champions (Motivational)","artist":"Queen","year":1977,"duration":"2:59"},
    {"title":"Don't Stop Me Now (Motivational)","artist":"Queen","year":1978,"duration":"3:29"},
    {"title":"I Believe I Can Fly","artist":"R. Kelly","year":1996,"duration":"5:20"},
    {"title":"Man in the Mirror","artist":"Michael Jackson","year":1988,"duration":"5:19"},
    {"title":"Beat It","artist":"Michael Jackson","year":1982,"duration":"4:18"},
    {"title":"Started From the Bottom","artist":"Drake","year":2013,"duration":"2:54"},
    {"title":"HUMBLE.","artist":"Kendrick Lamar","year":2017,"duration":"2:57"},
    {"title":"Alright","artist":"Kendrick Lamar","year":2015,"duration":"3:39"},
    {"title":"DNA.","artist":"Kendrick Lamar","year":2017,"duration":"3:06"},
    {"title":"POWER (Motivational)","artist":"Kanye West","year":2010,"duration":"4:52"},
    {"title":"Stronger (Motivational)","artist":"Kanye West","year":2007,"duration":"5:11"},
    {"title":"All of the Lights","artist":"Kanye West","year":2010,"duration":"5:00"},
    {"title":"Can't Tell Me Nothing","artist":"Kanye West","year":2007,"duration":"4:32"},
    {"title":"Good Life (Motivational)","artist":"Kanye West ft. T-Pain","year":2007,"duration":"3:27"},
    {"title":"Run the World (Girls)","artist":"Beyoncé","year":2011,"duration":"3:56"},
    {"title":"Formation","artist":"Beyoncé","year":2016,"duration":"3:26"},
    {"title":"Flawless","artist":"Beyoncé","year":2013,"duration":"4:11"},
    {"title":"Crazy in Love","artist":"Beyoncé ft. Jay-Z","year":2003,"duration":"3:56"},
    {"title":"Single Ladies","artist":"Beyoncé","year":2008,"duration":"3:13"},
    {"title":"Respect","artist":"Aretha Franklin","year":1967,"duration":"2:28"},
    {"title":"A Change Is Gonna Come","artist":"Sam Cooke","year":1964,"duration":"3:11"},
    {"title":"Imagine","artist":"John Lennon","year":1971,"duration":"3:03"},
    {"title":"One Moment in Time","artist":"Whitney Houston","year":1988,"duration":"5:22"},
    {"title":"The Climb","artist":"Miley Cyrus","year":2009,"duration":"3:55"},
    {"title":"Ain't No Mountain High Enough (Diana Ross)","artist":"Diana Ross","year":1970,"duration":"3:31"},
    {"title":"I Will Survive","artist":"Gloria Gaynor","year":1978,"duration":"3:18"},
    {"title":"Never Give Up","artist":"Sia","year":2016,"duration":"3:38"},
    {"title":"Alive","artist":"Sia","year":2015,"duration":"4:23"},
    {"title":"Elastic Heart","artist":"Sia","year":2013,"duration":"4:17"},
    {"title":"Chandelier (Motivational)","artist":"Sia","year":2014,"duration":"3:36"}
  ],
  "healing": [
    {"title":"Someone Like You (Acoustic)","artist":"Adele","year":2011,"duration":"4:29"},
    {"title":"Back to December","artist":"Taylor Swift","year":2010,"duration":"4:54"},
    {"title":"Tadap Tadap","artist":"KK","year":2003,"duration":"4:58"},
    {"title":"Judaai (Reprise)","artist":"Arijit Singh","year":2011,"duration":"4:10"},
    {"title":"Skin (Emotional)","artist":"Raghu Dixit","year":2010,"duration":"4:00"},
    {"title":"Stay With Me","artist":"Sam Smith","year":2014,"duration":"2:52"},
    {"title":"Kabhi Kabhi Aditi","artist":"Rahat Fateh Ali Khan","year":2008,"duration":"3:36"},
    {"title":"Somebody That I Used To Know","artist":"Gotye ft. Kimbra","year":2011,"duration":"4:04"},
    {"title":"Bhula Dena (Acoustic)","artist":"Mustafa Zahid","year":2008,"duration":"4:05"},
    {"title":"Apologize","artist":"OneRepublic","year":2007,"duration":"3:26"},
    {"title":"Ain't No Sunshine","artist":"Bill Withers","year":1971,"duration":"2:04"},
    {"title":"Jab Tak","artist":"Armaan Malik","year":2016,"duration":"3:34"},
    {"title":"Someone You Loved (Piano)","artist":"Lewis Capaldi","year":2018,"duration":"3:30"},
    {"title":"Kabira (Sad)","artist":"Arijit Singh","year":2013,"duration":"4:12"},
    {"title":"Let Her Go (Sad)","artist":"Passenger","year":2012,"duration":"4:21"},
    {"title":"Dil Ke Paas","artist":"Kishore Kumar (sad)","year":1983,"duration":"3:45"},
    {"title":"When I Was Your Man (Piano)","artist":"Bruno Mars","year":2012,"duration":"3:40"},
    {"title":"Jism 2 Title","artist":"Arijit Singh","year":2012,"duration":"4:00"},
    {"title":"Naina (Sad)","artist":"Arijit Singh","year":2016,"duration":"4:20"},
    {"title":"All I Want","artist":"Kodaline","year":2013,"duration":"5:07"},
    {"title":"Un-break My Heart","artist":"Toni Braxton","year":1996,"duration":"4:29"},
    {"title":"Tumhi Ho Bandhu","artist":"Neeraj Shridhar (mellow)","year":2009,"duration":"4:10"},
    {"title":"The Night We Met","artist":"Lord Huron","year":2015,"duration":"3:28"},
    {"title":"Humsafar (Sad)","artist":"Akhtar Chanal","year":2013,"duration":"4:20"},
    {"title":"Jeene Bhi De","artist":"Arijit Singh","year":2019,"duration":"3:34"},
    {"title":"Tere Bina (Sad)","artist":"A.R. Rahman","year":2006,"duration":"5:02"},
    {"title":"Say Something","artist":"A Great Big World & Christina Aguilera","year":2013,"duration":"3:50"},
    {"title":"Nila Kaigirathu","artist":"Tamil Classic (sad)","year":1995,"duration":"4:30"},
    {"title":"Jar of Hearts","artist":"Christina Perri","year":2010,"duration":"3:33"},
    {"title":"Kabhi Alvida Naa Kehna (Sad)","artist":"Arijit Singh","year":2006,"duration":"4:58"},
    {"title":"The Blower's Daughter","artist":"Damien Rice","year":2002,"duration":"4:42"},
    {"title":"Tum Se Hi (Sad)","artist":"Mohit Chauhan","year":2006,"duration":"5:30"},
    {"title":"Hurt (Emotional)","artist":"Johnny Cash","year":2002,"duration":"3:38"},
    {"title":"Dil Ibaadat (Sad)","artist":"Atif Aslam","year":2006,"duration":"4:25"},
    {"title":"Channa Mereya (Sad)","artist":"Arijit Singh","year":2016,"duration":"4:56"},
    {"title":"Lost Without You","artist":"Freya Ridings","year":2017,"duration":"3:50"},
    {"title":"Tum Hi Ho (Acoustic)","artist":"Arijit Singh","year":2013,"duration":"4:10"},
    {"title":"All I Want (Acoustic)","artist":"Kodaline","year":2013,"duration":"3:58"},
    {"title":"Someone Like You (Piano)","artist":"Adele","year":2011,"duration":"3:50"},
    {"title":"Hello","artist":"Adele","year":2015,"duration":"4:55"},
    {"title":"Kabhi Jo Baadal Barse (Sad)","artist":"Arijit Singh","year":2013,"duration":"5:17"},
    {"title":"You Are Not Alone","artist":"Michael Jackson","year":1995,"duration":"4:57"},
    {"title":"Tujhse Naraz Nahi Zindagi","artist":"Lata Mangeshkar","year":1983,"duration":"5:04"},
    {"title":"Happier","artist":"Marshmello ft. Bastille","year":2018,"duration":"3:34"},
    {"title":"The Scientist (Piano)","artist":"Coldplay","year":2002,"duration":"5:09"},
    {"title":"Fix You (Acoustic)","artist":"Coldplay","year":2005,"duration":"4:55"},
    {"title":"Yellow","artist":"Coldplay","year":2000,"duration":"4:26"},
    {"title":"The One That Got Away","artist":"Katy Perry","year":2011,"duration":"3:47"},
    {"title":"Grenade","artist":"Bruno Mars","year":2010,"duration":"3:42"},
    {"title":"It Will Rain","artist":"Bruno Mars","year":2011,"duration":"4:17"},
    {"title":"Too Good at Goodbyes","artist":"Sam Smith","year":2017,"duration":"3:21"},
    {"title":"I'm Not the Only One","artist":"Sam Smith","year":2014,"duration":"3:59"},
    {"title":"Lay Me Down (Acoustic)","artist":"Sam Smith","year":2014,"duration":"4:13"},
    {"title":"Like I Can","artist":"Sam Smith","year":2014,"duration":"2:47"},
    {"title":"Leave Your Lover","artist":"Sam Smith","year":2014,"duration":"3:35"},
    {"title":"Life Support","artist":"Sam Smith","year":2014,"duration":"3:42"},
    {"title":"Not In That Way","artist":"Sam Smith","year":2014,"duration":"3:44"},
    {"title":"Make It to Me","artist":"Sam Smith","year":2014,"duration":"3:18"},
    {"title":"Restart","artist":"Sam Smith","year":2014,"duration":"4:11"},
    {"title":"Good Thing","artist":"Sam Smith","year":2014,"duration":"3:08"},
    {"title":"Nirvana","artist":"Sam Smith","year":2014,"duration":"3:11"},
    {"title":"Palace","artist":"Sam Smith","year":2017,"duration":"3:19"},
    {"title":"Pray","artist":"Sam Smith","year":2017,"duration":"3:42"},
    {"title":"One Last Song","artist":"Sam Smith","year":2017,"duration":"3:03"},
    {"title":"Midnight Train","artist":"Sam Smith","year":2017,"duration":"3:16"},
    {"title":"Burning","artist":"Sam Smith","year":2017,"duration":"3:20"},
    {"title":"HIM","artist":"Sam Smith","year":2017,"duration":"3:17"},
    {"title":"Baby, You Make Me Crazy","artist":"Sam Smith","year":2017,"duration":"3:06"},
    {"title":"No Peace","artist":"Sam Smith ft. YEBBA","year":2017,"duration":"3:18"},
    {"title":"Scars","artist":"Sam Smith","year":2017,"duration":"3:40"},
    {"title":"One Day at a Time","artist":"Sam Smith","year":2017,"duration":"3:22"},
    {"title":"Nothing Left for You","artist":"Sam Smith","year":2017,"duration":"3:20"},
    {"title":"The Thrill of It All","artist":"Sam Smith","year":2017,"duration":"3:28"},
    {"title":"Say It First","artist":"Sam Smith","year":2017,"duration":"4:09"},
    {"title":"How Do You Sleep?","artist":"Sam Smith","year":2019,"duration":"3:22"},
    {"title":"To Die For","artist":"Sam Smith","year":2020,"duration":"3:17"},
    {"title":"I'm Ready","artist":"Sam Smith & Demi Lovato","year":2020,"duration":"3:04"},
    {"title":"Fire on Fire","artist":"Sam Smith","year":2018,"duration":"3:12"},
    {"title":"Promises","artist":"Calvin Harris & Sam Smith","year":2018,"duration":"3:18"},
    {"title":"Dancing With a Stranger","artist":"Sam Smith & Normani","year":2019,"duration":"2:52"},
    {"title":"I Feel Love","artist":"Sam Smith","year":2019,"duration":"3:39"},
    {"title":"Diamonds","artist":"Sam Smith","year":2020,"duration":"3:30"},
    {"title":"My Oasis","artist":"Sam Smith ft. Burna Boy","year":2020,"duration":"2:58"},
    {"title":"So Serious","artist":"Sam Smith","year":2020,"duration":"3:17"},
    {"title":"Dance ('Til You Love Someone Else)","artist":"Sam Smith","year":2020,"duration":"3:14"},
    {"title":"For the Lover That I Lost","artist":"Sam Smith","year":2020,"duration":"2:57"},
    {"title":"Breaking Hearts","artist":"Sam Smith","year":2020,"duration":"3:20"},
    {"title":"Another One","artist":"Sam Smith","year":2020,"duration":"3:03"},
    {"title":"Love Goes","artist":"Sam Smith","year":2020,"duration":"3:12"},
    {"title":"Kids Again","artist":"Sam Smith","year":2020,"duration":"3:13"},
    {"title":"Forgive Myself","artist":"Sam Smith","year":2020,"duration":"2:54"},
    {"title":"Young","artist":"Sam Smith","year":2020,"duration":"3:21"},
    {"title":"Like I Can (Acoustic)","artist":"Sam Smith","year":2014,"duration":"2:47"},
    {"title":"Drowning Shadows","artist":"Sam Smith","year":2015,"duration":"3:27"},
    {"title":"Writing's on the Wall","artist":"Sam Smith","year":2015,"duration":"4:38"},
    {"title":"Omen","artist":"Disclosure ft. Sam Smith","year":2015,"duration":"3:40"},
    {"title":"Latch (Acoustic Version)","artist":"Disclosure ft. Sam Smith","year":2012,"duration":"4:16"}
  ]
}

module.exports = songs